spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/project_cloud?useLegacyDatetimeCode=false&serverTimezone=America/Bogota
    username: root
    password: "{Cristian;8"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true

server:
  servlet:
    context-path: /api
  port: 8080
  error:
    include-message: always